
language: c

os:
   - linux

compiler: gcc

dist: bionic

sudo: required

addons:
   apt:
      update: true
      packages:
         - build-essential
         - kernel-headers-$(uname -r)
         - gcc-8

script:
   - make
