
language: c

os:
   - linux

compiler: gcc

dist: bionic
sudo: required

before_install:
   - export KVER="5.3.0-1004-gcp"
   - export KSRC="/usr/src/linux-headers-$KVER"
   - sudo apt-get update
   - sudo apt-get install -y build-essential linux-headers-$KVER gcc-8
   - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 10
   - sudo update-alternatives --set gcc /usr/bin/gcc-8

script:
   - make
