
language: c

os:
   -linux

compiler: gcc

dist: bionic

sudo: required

addons:
   apt:
      sources:
         - ubuntu-toolchain-r-test
      packages:
         - build-essential
         - kernel-headers-$(uname -r)

script:
   - make
